const VALID_CODEMIRROR_THEMES = [
  "abcdef",
  "abyss",
  "androidstudio",
  "andromeda",
  "atomone",
  "aura",
  "bbedit",
  "basic light",
  "basic dark",
  "bespin",
  "copilot",
  "dracula",
  "darcula",
  "duotone light",
  "duotone dark",
  "eclipse",
  "github light",
  "github dark",
  "gruvbox dark",
  "gruvbox light",
  "material light",
  "material dark",
  "monokai",
  "monokai dimmed",
  "kimbie",
  "noctis-lilac",
  "nord",
  "okaidia",
  "quietlight",
  "red",
  "solarized light",
  "solarized dark",
  "sublime",
  "tokyo-night",
  "tokyo-night-storm",
  "tokyo-night-day",
  "tomorrow-night-blue",
  "white dark",
  "white light",
  "vscode",
  "xcode light",
  "xcode dark"
];